concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "runner_2"
  url = "http://gitlab_app/"
#  url = "http://gitlab.local/"
  token = "WKC6fVo5Tgy7DE2TZHLK"
  executor = "docker"
#  clone_url = "http://gitlab.local"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker:latest"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache", "/var/run/docker.sock:/var/run/docker.sock","/dev/fuse:/dev/fuse"]
    shm_size = 0
    network_mode = "host"
